### PR TITLE
fix aliased variables being emmited twice

### PR DESCRIPTION
**Pull request by MonsieurMan**
Hi there, this is just a quick fix for a bug I had.

Aliased tokens with different modes were emitted twice (with two modes) as there were two place in the code where modes were taken into account.

This removes the loop in the `processAliasModes` fn, just keeping L98 which is already looping over modes.

I didn't tested it with more than two modes for now.

---

Thanks for the plugin, I'm doing research for implementing a multi-brand design system and I'll maybe use it, could contribute more if it is the case and you're open to it.

### CODE REVIEW

**Comment by lukasoppermann** [comment]
Hey @MonsieurMan this makes sense. 

Could you explain a way to test this to me?

How to I reproduce the issue with `double variables`? What setup do I need to create this? Afterward I can test this.

**Comment by JackHowa** [comment]
> @JackHowa this would be great. All we need is a way to test this and than we can merge it.

Cool, working on it now.

**Comment by JackHowa** [comment]
I like this attempt and appreciate the movement on it. But I tested this locally and it still mistook which mode was referring to which reference token by loading the in-development manifest

**Comment by JackHowa** [comment]
This works as expected for me locally. I will work on trying to unit test extractTokens. But will involve mocking figma's api

**Comment by JackHowa** [comment]
@lukasoppermann @MonsieurMan thanks for your work on this and patience. I have added some tests in a separate pr off the default that shows the alias modes emitting two values to show https://github.com/lukasoppermann/design-tokens/pull/299/files#diff-18b59c301a30dbea8cef574b8e83d81e812fa126a021df0860ff518f3dd21035R17

**Comment by lukasoppermann** [comment]
@JackHowa can you please resolve conflicts? I think you know better what is correct.

**Comment by JackHowa** [comment]
> @JackHowa can you please resolve conflicts? I think you know better what is correct.

sorry, this isn't my pr. looks like my pr was just merged! https://github.com/lukasoppermann/design-tokens/pull/300 🥳

**Comment by lukasoppermann** [comment]
@JackHowa sorry, I completely missed this the whole time. 🤦

**Comment by JackHowa** [comment]
> @JackHowa sorry, I completely missed this the whole time. 🤦

hahah no worries at all. thanks for the quick replies. your plugin is a lifesaver for my org

**Pull request closed without merging**
