### PR TITLE
add a button solely for saving the settings.

### PR DESCRIPTION
**Pull request by hayawata3626**
Related #267

UI

スクリーンショット 2023-08-26 15 37 55

Please let me know if there are any issues with the placement of the button or if anything feels out of place.

### CODE REVIEW

**Comment by hayawata3626** [comment]
@lukasoppermann 
I agree!
> So if you just want to change settings, you change them and click the X if you want to export you click export afterwards. WDYT?

I will do this.
- Any change triggers an auto-save
- we remove the cancel button
- we rename the save & export to export

**Comment by hayawata3626** [comment]
@lukasoppermann
I pushed the code.

**Comment by hayawata3626** [comment]
@lukasoppermann 
If there are any use cases that are not supported, we will correct them.

**Comment by lukasoppermann** [comment]
Looks good, sorry it took so long to review.

**Pull request merged**
