### PR TITLE
Excluded collections containing a specific string from the export target

### PR DESCRIPTION
**Pull request by hayawata3626**
Related https://github.com/lukasoppermann/design-tokens/discussions/270

**Collections**
スクリーンショット 2023-09-17 21 57 57

**Exported JSON**
スクリーンショット 2023-09-17 21 58 56

### CODE REVIEW

**Comment by hayawata3626** [comment]
@lukasoppermann 
The following part of the collection contains prefixes _ and . in the following section, should I add a description that does not export the collection as well?
スクリーンショット 2023-09-21 19 40 53

**Comment by lukasoppermann** [comment]
@hayawata3626 yes please. 🙏

**Comment by hayawata3626** [comment]
@lukasoppermann 
I added. :pray:

**Comment by lukasoppermann** [comment]
Hey, first of all, could you rebase so that you only have relevant commits?

I add some comments, we need to adjust it to make it work with the settings

**Comment by hayawata3626** [comment]
@lukasoppermann 
Thank you for your reply.
I will modify it!

**Comment by hayawata3626** [comment]
@lukasoppermann 
Sorry, I responded with another [PR](https://github.com/lukasoppermann/design-tokens/pull/276). Please review.
I will close this PR.

**Pull request closed without merging**
