### PR TITLE
Issue #224 - Feature request - add a field for commit message on url …

### LINKED ISSUE #224: Feature Request: Add a field for commit message
When pushing to GitHub from the plugin, we need a way to specify what changed so that when a new version of the tokens are published we can have a change log (e.g. using https://github.com/semantic-release/semantic-release). With that we can use semantic-versioning conventions to know if the release is a breaking change or not (e.g. a token is removed, thus breaking, or just updated or added.)

### PR DESCRIPTION
**Pull request by derekwsgray**
Adds an optional per-export "message" on the URL Export dialog.

This fixed #224 and #169

### CODE REVIEW

**Comment by lukasoppermann** [comment]
Hey @derekwsgray, thanks for all typo changes. However could please move those to a different PR? This makes it easier to review this one.

**Review by lukasoppermann — CHANGES_REQUESTED** [review]
Please remove the changes to the dist folder from the PR. This will be generated when releasing. Thanks.

**Comment by derekwsgray** [comment]
> Hey @derekwsgray, thanks for all typo changes. However could please move those to a different PR? This makes it easier to review this one.

Reverted.

**Comment by derekwsgray** [comment]
> Please remove the changes to the dist folder from the PR. This will be generated when releasing. Thanks.

Reverted.

**Comment by derekwsgray** [comment]
Couldn't get it cleaned out properly so I just re-created a new PR off the proper issue number: https://github.com/lukasoppermann/design-tokens/pull/227

**Pull request closed without merging**
