### PR TITLE
#182: Added support for Gitlab URL export

### PR DESCRIPTION
**Pull request by dgmartin**
Setting up this PR to add support for Gitlab per #182. Once again please let me know if you need any changes here. I did my best based on my minor knowledge of web code. Thanks

### CODE REVIEW

**Comment by dgmartin** [comment]
Rebased the branch with the latest updates from Main.

@lukasoppermann  before merging this in can you please run some tests with export. My friend and I are seeing some issues on our end using the "main" branch (not these changes) but we aren't sure if it's just our environment or not. Essentially the Save & Export button doesn't seem to do anything. We are still trying to determine if its just something we are doing wrong before I submit a ticket but your feedback would be helpful. Thank you.

**Comment by lukasoppermann** [comment]
Hey @dgmartin two "issues":
1. You should change the height for the window https://github.com/lukasoppermann/design-tokens/blob/main/src/config/config.ts#L14 to `650`
2. `Ref` should be renamed to something like "Reference", currently the tooltip is cut off.

Is the Save & Exit not working in your version or the released version? Are you talking about the "export to url" screen?

**Comment by dgmartin** [comment]
@lukasoppermann I pushed the changes you requested. 

As far as the issue I was seeing, my friend and I saw this happen with the release version and, yes, I'm referring to to the "export to url" screen. Again we are not sure this is just something we are doing wrong but it does seem to be an issue. Neither of us are very familiar with web development so we are limited in our debugging skills. I was hoping you could perform a test run or two in order to confirm/deny the issue.

**Comment by lukasoppermann** [comment]
So @dgmartin any news? Is this ready to be merged?

**Comment by dgmartin** [comment]
@lukasoppermann I'm happy to report the issue on our end was due to a VPN misconfiguration and not due to the plugin. Once the VPN was properly configured the plugin worked as expected. Please disregard my previous concerns and I apologize for any extra work this may have caused you. This should be good to go.

**Comment by lukasoppermann** [comment]
Hey @dgmartin I published your PR now. 👍 
As I can't verify gitlab, please verify it is all working according to plan.

Cheers and thanks for the great work,
Lukas

**Pull request merged**
